apiVersion: v1
kind: ConfigMap
metadata:
  name: basket-cm
  labels:
    app: eshop
    service: basket
data:
  ASPNETCORE_ENVIRONMENT: Development
  AzureServiceBusEnabled: "False"
  ConnectionString: basketdata
  EventBusConnection: rabbitmq
  identityUrl: http://identity-api
  IdentityUrlExternal: {{ .Values.protocol }}://{{ .Values.host }}/identity
  OrchestratorType: K8S
  PATH_BASE: /basket-api